name: Code Quality and Tests

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npx vitest --coverage
            - name: Report Coverage
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
            - name: Run code quality checks
              run: npm run lint
